### ISSUE TITLE
安装测试报错

### ISSUE THREAD

**Issue by daniel198609** [tencentyun/elasticsearch-repository-cos#1]
![image](https://user-images.githubusercontent.com/31444594/75651967-e2e82000-5c94-11ea-9fea-98ff53083dad.png)

**Comment by Ethan-Zhang** [comment]
已修复，是IT集成测试中的名字写错了，麻烦帮忙继续测试~

**Comment by daniel198609** [comment]
我已经搞定了 谢谢
