### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by PaulWang92115** [tencentyun/elasticsearch-repository-cos#11]
version 7.6 , gradle build failed
> Task :processTestResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':processTestResources' (type 'ProcessResources').
> No value has been specified for property 'accessKeyId'.
> No value has been specified for property 'accessKeySecret'.
> No value has been specified for property 'cosBasePath'.
> No value has been specified for property 'cosBucket'.

**Comment by Ethan-Zhang** [comment]
@YinshawnRao

**Comment by wuyinan0126** [comment]
`String cosAccessKeyId = System.getenv("qcloud_cos_access_key_id")
String cosAccessKeySecret = System.getenv("qcloud_cos_access_key_secret")
String cosBucket = System.getenv("qcloud_cos_bucket")
String cosBasePath = System.getenv("qcloud_cos_base_path")
String cosRegion = System.getenv("qcloud_cos_region")`

building will run test with the params above. please set the params in system env.
