### ISSUE TITLE
腾讯云的COS禁止外网访问

### ISSUE THREAD

**Issue by edwardzcy** [tencentyun/elasticsearch-repository-cos#16]
公司内部的cos平台，无法通过外网访问，es的数据通过cos快照迁移的时候，会被禁止
<img width="1962" alt="image" src="https://user-images.githubusercontent.com/20805378/168759470-a328c51f-04e9-4c3d-a232-ee48a66869aa.png">

**Comment by Ethan-Zhang** [comment]
应该有支持的参数，可以直接定于repository的url  @wuyinan0126
